/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LoadingBarFrame.java
 *
 * Created on Mar 2, 2010, 9:07:35 PM
 */

package pacchess.base.gui;

import java.awt.Image;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.HashMap;
import pacchess.base.gui.thread.ImageResizer;
import pacchess.piece.Allegiance;
import pacchess.piece.Piece;

/**
 *
 * @author hrothgar
 */
public class LoadingBarFrame
	extends javax.swing.JFrame
	implements PropertyChangeListener
{

    private ImageResizer res;

    /** Creates new form LoadingBarFrame */
    public LoadingBarFrame(String ip, int s,HashMap<Allegiance,HashMap<Piece,Image>> il,
	    HashMap<Allegiance,HashMap<Piece,Image>> is,PacChessGUI gui) {
        initComponents();
	setVisible(true);
	res = new ImageResizer(ip,s,il,is,gui);
	res.addPropertyChangeListener(this);
    }

    public void execute()
    {
	res.execute();
    }

     /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progressBar = new javax.swing.JProgressBar();
        label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        label.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        label.setText("Please Wait...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(label)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(label)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new LoadingBarFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables

    public boolean isDone()
    {
	return res.isDone();
    }

    public void propertyChange(PropertyChangeEvent pce) {
	if("progress" == pce.getPropertyName())
	{
	    int progress = (Integer) pce.getNewValue();
	    progressBar.setValue(progress);
	}
    }

}
